Publish JSON Test

diff --git a/.github/workflows/lw-github-actions.yml b/.github/workflows/lw-github-actions.yml
--- a/.github/workflows/lw-github-actions.yml
+++ b/.github/workflows/lw-github-actions.yml
@@ -30,28 +30,39 @@ jobs:
           LW_API_KEY: ${{ secrets.API_KEY }}
           LW_API_SECRET: ${{ secrets.API_SECRET_TOKEN }}
         run: |
+             # Setup 
              env | grep "GITHUB_\|LW_\|CI_" > env.list
              echo "SCAN_COMMAND=tf-scan" >> env.list
              echo "WORKSPACE=src" >> env.list
              #echo "EXIT_FLAG='Critical'" >> env.list 
-             echo "JUNIT_OUTPUT_FILE=/tmp/lacework.junit.xml"  >> env.list
+             echo "JUNIT_OUTPUT_FILE=/tmp/lacework-report.junit.xml"  >> env.list
+             echo "JSON_OUTPUT_FILE=/tmp/lacework-report.json"  >> env.list
+             
              # Run the Scan
              docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
+             
              # Copy the report outside the container
              CONTAINER_ID=$(docker ps -a |grep lacework |head -n1 |cut -d ' ' -f1)
-             docker container cp "$CONTAINER_ID:/tmp/lacework.junit.xml" .
-             docker inspect lacework/codesec-iac:latest
-      - name: Publish Lacework Junit Report
-        uses: mikepenz/action-junit-report@v4
-        # if: success() || failure() # always run even if the previous step fails
+             docker container cp "$CONTAINER_ID:/tmp/lacework-report*" .
+
+      # - name: Publish Lacework Junit Report
+      #   uses: mikepenz/action-junit-report@v4
+      #   # if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
+      #     report_paths: 'lacework.junit.xml'
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        if: always()
         with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          report_paths: 'lacework.junit.xml'
+          files: |
+            lacework-report.json
+          
       - name: 'Upload Artifact'
         uses: actions/upload-artifact@v3
         with:
           name: Lacework Junit Report
-          path: lacework.junit.xml
+          path: lacework-report*
   Terraform-deploy:
     runs-on: ubuntu-latest
     needs: Lacework-Scan
